


module.exports = Object.freeze({

    SEND_DELIVERY:'SEND_DELIVERY',

SEND_MODIFY_ORDER:'SEND_MODIFY_ORDER',
WITHDRAW_MODIFY_ORDER:'WITHDRAW_MODIFY_ORDER',
ACCEPT_MODIFY_ORDER:'ACCEPT_MODIFY_ORDER',
DECLINE_MODIFY_ORDER:'DECLINE_MODIFY_ORDER',


SEND_EXTEND_ORDER:'SEND_EXTEND_ORDER',
WITHDRAW_EXTEND_ORDER:'WITHDRAW_EXTEND_ORDER',
ACCEPT_EXTEND_ORDER:'ACCEPT_EXTEND_ORDER',
DECLINE_EXTEND_ORDER:'DECLINE_EXTEND_ORDER',


SEND_CANCEL_ORDER:'SEND_CANCEL_ORDER',
WITHDRAW_CANCEL_ORDER:'WITHDRAW_CANCEL_ORDER',
ACCEPT_CANCEL_ORDER:'ACCEPT_CANCEL_ORDER',
DECLINE_CANCEL_ORDER:'DECLINE_CANCEL_ORDER',



ACCEPT_DELIVERY:'ACCEPT_DELIVERY'
});

