const mongoose=require("mongoose");
const ProfileSchema= new mongoose.Schema({
    user:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'user'
    },
    company:{
        type:String
    },
    website:{
        type:String
    },
    location:{
        type:String
    },
    status:{
        type:String,
        requried:true
    },  
    skills:{
        type:[String],
        requried:true
    },
    bio:{
        type:String
    },
    githubusername:{
        type:String
    },
    experience:[
        {
            title:{
                type:String,
                requried:true
            },
            company:{
                type:String,
                requried:true
            },
            location:{
                type:String,
               
            },
            from:{
                type:Date,
                requried:true
            },
            to:{
                type:Date
            },
            current:{
                type:String,
                requried:true
            },
            description:{
                type:String,
                requried:true
            },
        }],

    education:[
        {
            school:{
                type:String,
                requried:true
            },
            degree:{
                type:String,
                requried:true
            },
            fieldofstudy:{
                type:String,
                
            },
            from:{
                type:Date,
                requried:true
            },
            to:{
                type:Date
            },
            current:{
                type:Boolean,
                requried:true
            },
            description:{
                type:String,
                requried:true
            },
        }],
    social:{
        youtube:{
            type:String
        },
        twitter:{
            type:String
        },
        facebook:{
            type:String
        },
        linkedin:{
            type:String
        },
        instagram:{
            type:String
        },
    }

})
module.exports=Profile=mongoose.model('profile',ProfileSchema);